# Runcard for contaminated PDF fit with SIMUnet
#
############################################################
description: "Runcard template for a contaminated PDF fit with BSM physics injected in the data, defined as linear combinations of the SMEFT Warsaw basis operators."

############################################################
# frac: training fraction of datapoints for the PDFs
# QCD: apply QCD K-factors
# EWK: apply electroweak K-factors
# simu_fac: fit BSM coefficients using their K-factors in the dataset
# use_fixed_predictions: if set to True it removes the PDF dependence of the dataset
# sys: systematics treatment (see systypes)

############################################################
dataset_inputs:
  ### 'Standard' datasets ###
  - dataset: NMCPD_dw_ite
    frac: 0.75
  - dataset: NMC
    frac: 0.75
  - dataset: SLACP_dwsh
    frac: 0.75
  - dataset: HERACOMBCCEP
    frac: 0.75
  - dataset: HERACOMB_SIGMARED_C
    frac: 0.75
  - dataset: HERACOMB_SIGMARED_B
    frac: 0.75
  - dataset: DYE886R_dw_ite
    frac: 0.75
    cfac: ["QCD"]
  - dataset: DYE886P
    frac: 0.75
    cfac: ["QCD"]
  - dataset: DYE605_dw_ite
    frac: 0.75
    cfac: ["QCD"]
  - dataset: DYE906R_dw_ite
    frac: 0.75
    cfac: ["ACC", "QCD"]
  - dataset: CDFZRAP_NEW
    frac: 0.75
    cfac: ["QCD"]
  - dataset: D0ZRAP_40
    frac: 0.75
    cfac: ["QCD"]
  - dataset: D0WMASY
    frac: 0.75
    cfac: ["QCD"]
  - dataset: ATLASWZRAP36PB
    frac: 0.75
    cfac: ["QCD"]

  ### 'Contaminated' datasets ###
  - dataset: CMSDY1D12
    frac: 0.75
    cfac: ["QCD", "EWK"]
    contamination: "EFT_LO"
  - dataset: CMS_HMDY_13TEV
    frac: 0.75
    cfac: ["QCD", "EWK"]
    contamination: "EFT_LO"
  - dataset: ATLASDY2D8TEV
    frac: 0.75
    cfac: ["QCDEWK"]
    contamination: "EFT_LO"
  - dataset: ATLASZHIGHMASS49FB
    frac: 0.75
    cfac: ["QCD"]
    contamination: "EFT_LO"

fixed_pdf_fit: false
# load_weights_from_fit: 221103-jmm-no_top_1000_iterated # If this is uncommented, training starts here.

############################################################
closuretest:
  filterseed: 0
  fakedata: true
  fakepdf: NNPDF40_nnlo_as_01180
  errorsize: 1.0
  fakenoise: true
  rancutprob: 1.0
  rancutmethod: 0
  rancuttrnval: false
  printpdf4gen: false
  contamination_parameters:
    - name: "W"
      value: 0.00008
      linear_combination:
        Olq3: -15.94
    - name: "Y"
      value: 1
      linear_combination:
        Olq1: 1.51606
        Oed: -6.0606
        Oeu: 12.1394
        Olu: 6.0606
        Old: -3.0394
        Oqe: 3.0394

seed: 0
rngalgo: 0

############################################################
datacuts:
  t0pdfset: NNPDF40_nnlo_as_01180
  q2min: 3.49
  w2min: 12.5

############################################################
theory:
  theoryid: 270

############################################################
trvlseed: 475038818
nnseed: 2394641471
mcseed: 1831662593
save: "weights.h5"
genrep: true

############################################################
parameters:
  nodes_per_layer: [25, 20, 8]
  activation_per_layer: [tanh, tanh, linear]
  initializer: glorot_normal
  optimizer:
    clipnorm: 6.073e-6
    learning_rate: 2.621e-3
    optimizer_name: Nadam
  epochs: 30000

  stopping_patience: 0.2
  layer_type: dense
  dropout: 0.0
  threshold_chi2: 3.5

############################################################
fitting:
  fitbasis: EVOL
  basis:
    - fl: sng
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [1.093, 1.121]
      largex: [1.486, 3.287]
    - fl: g
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [0.8329, 1.071]
      largex: [3.084, 6.767]
    - fl: v
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [0.5202, 0.7431]
      largex: [1.556, 3.639]
    - fl: v3
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [0.1205, 0.4839]
      largex: [1.736, 3.622]
    - fl: v8
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [0.5864, 0.7987]
      largex: [1.559, 3.569]
    - fl: t3
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [-0.5019, 1.126]
      largex: [1.754, 3.479]
    - fl: t8
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [0.6305, 0.8806]
      largex: [1.544, 3.481]
    - fl: t15
      pos: false
      trainable: false
      mutsize: [15]
      mutprob: [0.05]
      smallx: [1.087, 1.139]
      largex: [1.48, 3.365]

############################################################
positivity:
  posdatasets:
    - dataset: POSF2U
      maxlambda: 1e6
    - dataset: POSF2DW
      maxlambda: 1e6
    - dataset: POSF2S
      maxlambda: 1e6
    - dataset: POSFLL
      maxlambda: 1e6
    - dataset: POSDYU
      maxlambda: 1e10
    - dataset: POSDYD
      maxlambda: 1e10
    - dataset: POSDYS
      maxlambda: 1e10
    - dataset: POSF2C
      maxlambda: 1e6
    - dataset: POSXUQ
      maxlambda: 1e6
    - dataset: POSXUB
      maxlambda: 1e6
    - dataset: POSXDQ
      maxlambda: 1e6
    - dataset: POSXDB
      maxlambda: 1e6
    - dataset: POSXSQ
      maxlambda: 1e6
    - dataset: POSXSB
      maxlambda: 1e6
    - dataset: POSXGL
      maxlambda: 1e6

############################################################
integrability:
  integdatasets:
    - dataset: INTEGXT8
      maxlambda: 1e2
    - dataset: INTEGXT3
      maxlambda: 1e2

############################################################
debug: false
maxcores: 4
